"""Data models for AI-generated vocabulary flashcards and conversation practice."""

from __future__ import annotations

from typing import Any

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator


class VocabularyCard(BaseModel):
    """Represents a vocabulary flashcard generated by AI.

    The canonical schema is language-neutral: ``translation`` and
    ``example_translation`` are written in the user-selected explanation
    language. Legacy ``translation_pl`` / ``example_pl`` keys are still accepted
    so old autosaves and older provider responses continue to load.
    """

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    is_valid: bool = Field(default=True, description="Whether the input is a valid expression.")
    validation_error: str = Field(default="", description="Explanation when input validation fails.")
    suggested_correction: str = Field(default="", description="Suggested correction for invalid input.")
    explanation_language: str = Field(
        default="",
        description="User-selected language used for translations and short usage explanations.",
    )

    word_or_phrase: str = Field(description="The target-language word or phrase.")
    target_language: str = Field(description="Target language, for example English or Spanish.")
    part_of_speech: str = Field(description="Part of speech, e.g. noun, verb, adjective, phrase.")
    definition: str = Field(description="Short definition in the target language.")
    translation: str = Field(
        default="",
        validation_alias=AliasChoices("translation", "translation_pl"),
        description="Translation or short explanation in the selected explanation language.",
    )
    example: str = Field(description="Natural example sentence in the target language.")
    example_translation: str = Field(
        default="",
        validation_alias=AliasChoices("example_translation", "example_pl"),
        description="Translation of the example in the selected explanation language.",
    )
    synonyms: list[str] = Field(description="A short list of useful synonyms or close alternatives.")
    collocations: list[str] = Field(description="Common phrases, collocations, or usage patterns.")
    grammar_note: str = Field(description="Short grammar or usage note in the selected explanation language.")
    audio: str = Field(default="", description="Anki sound reference for the example sentence.")
    topic_fit: str = Field(
        default="",
        description="Provider self-check for topic fit: ok, weak, mismatch, or not_applicable.",
    )
    topic_warning: str = Field(
        default="",
        description="Provider explanation when the example may not fit the user topic/context.",
    )
    quality_warnings: list[str] = Field(
        default_factory=list,
        description="Provider self-check warnings surfaced before adding to Anki.",
    )
    used_form_in_example: str = Field(
        default="",
        description="Provider self-check: exact target form that appears in the example sentence.",
    )
    example_uses_target: bool | None = Field(
        default=None,
        description="Provider self-check: whether the example uses the target item or a valid inflected form.",
    )
    collocation_naturalness: str = Field(
        default="",
        description="Provider self-check for naturalness of the target collocation: ok, weak, or bad.",
    )
    translation_naturalness: str = Field(
        default="",
        description="Provider self-check for translation naturalness: ok, weak, or bad.",
    )

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_translation_keys(cls, data: Any) -> Any:
        """Accept old autosaves/provider JSON with translation_pl/example_pl."""
        if not isinstance(data, dict):
            return data
        normalized = dict(data)
        if "translation" not in normalized and "translation_pl" in normalized:
            normalized["translation"] = normalized.get("translation_pl") or ""
        if "example_translation" not in normalized and "example_pl" in normalized:
            normalized["example_translation"] = normalized.get("example_pl") or ""
        return normalized

    @property
    def translation_pl(self) -> str:
        """Backward-compatible alias for older UI/Anki code."""
        return self.translation

    @translation_pl.setter
    def translation_pl(self, value: str) -> None:
        self.translation = value

    @property
    def example_pl(self) -> str:
        """Backward-compatible alias for older UI/Anki code."""
        return self.example_translation

    @example_pl.setter
    def example_pl(self, value: str) -> None:
        self.example_translation = value

    def model_dump_legacy_compatible(self) -> dict[str, Any]:
        """Return canonical + legacy keys for autosaves and transitional UI code."""
        data = self.model_dump()
        data["translation_pl"] = self.translation
        data["example_pl"] = self.example_translation
        return data


class ConversationStart(BaseModel):
    """Represents the first question in a conversation practice session."""

    question: str = Field(description="A natural question in the target language.")


class ConversationFeedback(BaseModel):
    """Represents feedback after one learner response."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    feedback_language: str = Field(default="", description="Language used for the feedback field.")
    feedback: str = Field(
        default="",
        validation_alias=AliasChoices("feedback", "feedback_pl"),
        description="Short, helpful feedback in the selected feedback language.",
    )
    corrected_version: str = Field(
        description="Learner answer corrected without unnecessarily changing its meaning."
    )
    advanced_answer: str = Field(
        description="A richer model answer written at the selected learning level."
    )
    next_question: str = Field(description="Next conversation question in the target language.")
    suggested_vocabulary: list[str] = Field(
        description="Useful target-language words or phrases suitable for flashcards."
    )

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_feedback_key(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data
        normalized = dict(data)
        if "feedback" not in normalized and "feedback_pl" in normalized:
            normalized["feedback"] = normalized.get("feedback_pl") or ""
        return normalized

    @property
    def feedback_pl(self) -> str:
        """Backward-compatible alias for old conversation code."""
        return self.feedback

    @feedback_pl.setter
    def feedback_pl(self, value: str) -> None:
        self.feedback = value


class GrammarAnalysis(BaseModel):
    """Represents a sentence-first grammar explanation generated by AI."""

    sentence: str = Field(description="Original sentence in the target language.")
    target_language: str = Field(description="Language used for the sentence and explanations.")
    meaning: str = Field(description="Simple paraphrase of the sentence in the target language.")
    structure: str = Field(description="Short grammar pattern used in the sentence.")
    breakdown: list[str] = Field(
        description="Short explanations of the most important parts of the structure."
    )
    usage: str = Field(description="When and why the structure is used.")
    context_example: str = Field(
        description="A natural context that makes the original sentence meaningful."
    )
    contrasts: list[str] = Field(
        description="Short contrasts with similar structures or time references."
    )
    common_mistakes: list[str] = Field(
        description="Common incorrect forms followed by their corrected versions."
    )
