"""Data models for AI-generated vocabulary flashcards and conversation practice."""

from pydantic import BaseModel, Field


class VocabularyCard(BaseModel):
    """Represents a vocabulary flashcard generated by AI."""

    is_valid: bool = Field(default=True, description="Whether the input is a valid expression.")
    validation_error: str = Field(default="", description="Explanation when input validation fails.")
    suggested_correction: str = Field(default="", description="Suggested correction for invalid input.")
    explanation_language: str = Field(
        default="Polish",
        description="Language used for translations and short usage explanations.",
    )

    word_or_phrase: str = Field(description="The target-language word or phrase.")
    target_language: str = Field(description="Target language, for example English or Spanish.")
    part_of_speech: str = Field(description="Part of speech, e.g. noun, verb, adjective, phrase.")
    definition: str = Field(description="Short definition in the target language.")
    translation_pl: str = Field(description="Polish translation.")
    example: str = Field(description="Natural example sentence in the target language.")
    example_pl: str = Field(description="Polish translation of the example sentence.")
    synonyms: list[str] = Field(description="A short list of useful synonyms or close alternatives.")
    collocations: list[str] = Field(description="Common phrases, collocations, or usage patterns.")
    grammar_note: str = Field(description="Short grammar or usage note in Polish.")
    audio: str = Field(default="", description="Anki sound reference for the example sentence.")
    topic_fit: str = Field(
        default="",
        description="Provider self-check for topic fit: ok, weak, mismatch, or not_applicable.",
    )
    topic_warning: str = Field(
        default="",
        description="Provider explanation when the example may not fit the user topic/context.",
    )
    quality_warnings: list[str] = Field(
        default_factory=list,
        description="Provider self-check warnings surfaced before adding to Anki.",
    )


class ConversationStart(BaseModel):
    """Represents the first question in a conversation practice session."""

    question: str = Field(description="A natural question in the target language.")


class ConversationFeedback(BaseModel):
    """Represents feedback after one learner response."""

    feedback_pl: str = Field(description="Short, helpful feedback in Polish.")
    corrected_version: str = Field(
        description="Learner answer corrected without unnecessarily changing its meaning."
    )
    advanced_answer: str = Field(
        description="A richer model answer written at the selected learning level."
    )
    next_question: str = Field(description="Next conversation question in the target language.")
    suggested_vocabulary: list[str] = Field(
        description="Useful target-language words or phrases suitable for flashcards."
    )


class GrammarAnalysis(BaseModel):
    """Represents a sentence-first grammar explanation generated by AI."""

    sentence: str = Field(description="Original sentence in the target language.")
    target_language: str = Field(description="Language used for the sentence and explanations.")
    meaning: str = Field(description="Simple paraphrase of the sentence in the target language.")
    structure: str = Field(description="Short grammar pattern used in the sentence.")
    breakdown: list[str] = Field(
        description="Short explanations of the most important parts of the structure."
    )
    usage: str = Field(description="When and why the structure is used.")
    context_example: str = Field(
        description="A natural context that makes the original sentence meaningful."
    )
    contrasts: list[str] = Field(
        description="Short contrasts with similar structures or time references."
    )
    common_mistakes: list[str] = Field(
        description="Common incorrect forms followed by their corrected versions."
    )
