"""Data models for AI-generated vocabulary flashcards and conversation practice."""

from pydantic import BaseModel, Field


class VocabularyCard(BaseModel):
    """Represents a vocabulary flashcard generated by AI."""

    word_or_phrase: str = Field(description="The target-language word or phrase.")
    target_language: str = Field(description="Target language, for example English or Spanish.")
    part_of_speech: str = Field(description="Part of speech, e.g. noun, verb, adjective, phrase.")
    definition: str = Field(description="Short definition in the target language.")
    translation_pl: str = Field(description="Polish translation.")
    example: str = Field(description="Natural example sentence in the target language.")
    example_pl: str = Field(description="Polish translation of the example sentence.")
    synonyms: list[str] = Field(description="A short list of useful synonyms or close alternatives.")
    collocations: list[str] = Field(description="Common phrases, collocations, or usage patterns.")
    grammar_note: str = Field(description="Short grammar or usage note in Polish.")


class ConversationStart(BaseModel):
    """Represents the first question in a conversation practice session."""

    question: str = Field(description="A natural question in the target language.")


class ConversationFeedback(BaseModel):
    """Represents feedback after one learner response."""

    feedback_pl: str = Field(description="Short, helpful feedback in Polish.")
    corrected_version: str = Field(
        description="Learner answer corrected without unnecessarily changing its meaning."
    )
    advanced_answer: str = Field(
        description="A richer model answer written at the selected learning level."
    )
    next_question: str = Field(description="Next conversation question in the target language.")
    suggested_vocabulary: list[str] = Field(
        description="Useful target-language words or phrases suitable for flashcards."
    )
