"""Utilities for converting validated vocabulary cards into Anki fields."""

from __future__ import annotations

from html import escape

from src.domain.models import GrammarAnalysis, VocabularyCard


class VocabularyFieldBuilder:
    """Build HTML-safe Anki fields from a vocabulary card.

    The AI model returns plain text data. Anki card templates render HTML, so every
    text value must be escaped before it is sent to AnkiConnect. Short lists are
    rendered as styled ``span`` elements because the card CSS expects chips.
    """

    @classmethod
    def build_fields(cls, card: VocabularyCard) -> dict[str, str]:
        """Return Anki note fields for the custom vocabulary note type.

        Args:
            card: Validated vocabulary card generated by an AI provider.

        Returns:
            Mapping between Anki field names and HTML-safe field values.
        """
        return {
            "Word": cls.safe(card.word_or_phrase),
            "Language": cls.safe(card.target_language),
            "PartOfSpeech": cls.safe(card.part_of_speech),
            "TranslationPL": cls.safe(card.translation_pl),
            "Definition": cls.safe(card.definition),
            "Example": cls.safe(card.example),
            "ExamplePL": cls.safe(card.example_pl),
            "Synonyms": cls.chips(card.synonyms),
            "Collocations": cls.chips(card.collocations),
            "GrammarNote": cls.safe(card.grammar_note),
        }

    @staticmethod
    def safe(value: str) -> str:
        """Escape text for Anki HTML and preserve explicit line breaks."""
        return escape(value).replace("\n", "<br>")

    @classmethod
    def chips(cls, values: list[str]) -> str:
        """Render a list of short strings as HTML chips."""
        return " ".join(
            f'<span class="chip">{cls.safe(value)}</span>' for value in values
        )


class GrammarFieldBuilder:
    """Build HTML-safe Anki fields from a grammar analysis."""

    @classmethod
    def build_fields(cls, card: GrammarAnalysis) -> dict[str, str]:
        """Return Anki note fields for the grammar note type."""
        return {
            "Sentence": cls.safe(card.sentence),
            "Language": cls.safe(card.target_language),
            "Meaning": cls.safe(card.meaning),
            "Structure": cls.safe(card.structure),
            "Breakdown": cls.blocks(card.breakdown),
            "Usage": cls.safe(card.usage),
            "ContextExample": cls.safe(card.context_example),
            "Contrasts": cls.blocks(card.contrasts),
            "CommonMistakes": cls.blocks(card.common_mistakes),
        }

    @staticmethod
    def safe(value: str) -> str:
        """Escape text for Anki HTML and preserve explicit line breaks."""
        return escape(value).replace("\\n", "<br>")

    @classmethod
    def blocks(cls, values: list[str]) -> str:
        """Render a list of explanations as stacked HTML blocks."""
        return "".join(
            f'<div class="grammar-list-item">{cls.safe(value)}</div>'
            for value in values
        )
